version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports: ["1883:1883", "9001:9001"]
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: mf
      POSTGRES_PASSWORD: mf
      POSTGRES_DB: microfactory
    ports: ["5432:5432"]
  grafana:
    image: grafana/grafana:10.4.2
    ports: ["3000:3000"]
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
